### ISSUE TITLE
can't select songs from playlist

### ISSUE THREAD

**Issue by ronniebadmf** [BimmerGestalt/AAIdrive#166]
Can't select songs from playlist i.e. Liked Songs.
1. the playlist content only displays on the dashboard;
2. when selecting a title, it restarts the current track. 

Back and Next functions work ok - no issue.
version 1.2.2-240 on iDrive 6

**Comment by hufman** [comment]
Thank you for the bug report!
Can you confirm if this problem happens when playing other queues, such as an album or a playlist?

I believe you are encountering #96, a bug in the Spotify library that ignores the skipToIndex index and always plays the first track (or a random track if shuffle is enabled), but only when playing Liked Songs and any Podcasts. I've reported it to [Spotify](https://github.com/spotify/android-sdk/issues/267) but haven't heard any updates.

We don't have a good solution yet :( I apologize!

**Comment by daniel1v** [comment]
@hufman did you consider to check if skipToIndex finds the correct track and if it does not, to call skipNext repeatedly, until the desired song is found?

**Comment by hufman** [comment]
We have tried this idea, but there seems to be a rate limit in the control API and then it stops responding to further skipNext commands. There's also a slight complication when factoring in Shuffle status too.

**Comment by hufman** [comment]
Good evening! I believe this has been resolved with #263 and #419, please install the latest nightly build and try it out!

**Comment by ronniebadmf** [comment]
Hi Walter, I tried with version 1.3.28 and the issue persists. Thanks a lot!

**Comment by hufman** [comment]
Hmmm try downloading the latest build link again, the fix should be in version androidautoidrive-1.3-125 and the latest build should be version androidautoidrive-1.3-142.

**Comment by ronniebadmf** [comment]
Thank you.
I installed and am now on 1.3. 144. Unfortunately, the issue persists with
not being able to navigate through the liked songs.

**Comment by hufman** [comment]
As the code (especially related to Spotify) has changed significantly since the initial issue was filed, can you tell me more about what is going wrong? What music app(s) are you trying and experiencing issues with? Are you using the latest official Spotify version? Modded versions of Spotify are not supported. Do you have Spotify Premium?

**Comment by ronniebadmf** [comment]
Hi Walter,
I use Spotify 8.6.70.1102 under a premium subscription.
Until yesterday, I used an older version of AAIdrive. I believe it was
1.2.2 which you sent me back in December 2020.
With that version, I was able to browse through the liked songs playlist
from the car and pick any song.

I saw you closed issue #166 and mentioned the new version, so I downloaded
it. As mentioned earlier, I am now on 1.3.144 , yet the issue with not
being able to browse through liked songs came back again.

Let me know if you need more information.

Thanks
Dragos
