### ISSUE TITLE
GMap sreen issues

### ISSUE THREAD

**Issue by jezikk82** [BimmerGestalt/AAIdrive#44]
Hi,
 
I compiled the app with the GMaps in it and found some problems:
1. On the main screen Gmap preview and options to search a place or stop navi (see photo)
2. After you put search info where is no additional info on the place (e.g. city, address if the is more then one result and is hard to choose correct)
3. Navigation doesn't work, after you find place and click on it navi doesn't start.
4. Map doesn't fit the place on the screen (see photos).  (Look at the side panel on/off). Changing option from the app to show on the full screen 
5. Refresh rate is 1FPS or less. Disappointment :( Also very often maps just hangs and don't refresh the image for couple of seconds. 

Link with the photos: https://photos.app.goo.gl/NTFDtozeVWNhiBD39

**Comment by hufman** [comment]
I just pushed a fix for the main menu display bug, please test it out!
Note that there isn't a navigation experience, because reproducing the Google Navigation experience is against the EULA.
I have some ideas for the rest of the issues, stay tuned!

**Comment by jezikk82** [comment]
Hi, I tested this. See photo below. It's better but still rest of the issues persists. 

![20191210_162853](https://user-images.githubusercontent.com/7836767/70546691-0a38c080-1b70-11ea-815f-40f42b59c150.jpg)
![20191210_162846](https://user-images.githubusercontent.com/7836767/70546729-191f7300-1b70-11ea-8b1f-9c8935631bcc.jpg)

**Comment by jezikk82** [comment]
GMaps in the full screen mode.  Still, there is some resolution problem, as the map is not coverng full display. 
Sometime, there is also an issue that GMaps dont get fix (gsp data) and present as bellow only blue splash screen. 

![IMG_20191210_190646](https://user-images.githubusercontent.com/7836767/70606206-4b76b200-1bfc-11ea-8d90-81d28bb80a2c.jpg)

**Comment by jezikk82** [comment]
Resolutions of NBT i found are:
800 x 480
1280 x 480
1440 x 540
1920 x 720 
Side panel is 30% wide according to what I found.

So I suppose the app should ask for resolution and set exactly that size of GMap.

**Comment by hufman** [comment]
Thank you for this! I can easily get the resolution, you are correct. I haven't found a way to tell whether the sidebar is open, which is why it's a manual option.
I'd have to figure out what margin to take away because of the left and top bars. I opened ticket #50 to track the size issue specifically.
Thank you again!

**Comment by jezikk82** [comment]
Send me the file where map is set to 100% of the resolution. I will test it on 2 screens (1920px and 1280px wide). I'll try to calculate padding if needed.

**Comment by hufman** [comment]
Brilliant idea! Test out some changes in [this file](https://github.com/hufman/AndroidAutoIdrive/blob/master/app/src/main/java/me/hufman/androidautoidrive/carapp/maps/MapView.kt#L49), with `mapWidth` and `mapHeight`. I apologize for the poor code in this file.

**Comment by jezikk82** [comment]
I played a bit with the values in the file on the biggest resolution screen. 
For now it was based on hardcoded values and e.g. screen with resolution 1920 suits map with width 1860-1880px. Height should be around 690-700px. 

I don't know if map can be positioned with out this padding
Did you documented somewhere what each of this properties (setProperty(int, value)) mean:
viewFullMap.setProperty(20, -36)    // positionX
viewFullMap.setProperty(21, -10)    // positionY
viewFullMap.setProperty(9, mapWidth)
viewFullMap.setProperty(10, mapHeight)

I also got some strange behaviour withe the map images as you capture image in resolution 1000x400 (VirtualDisplayScreenCapture):
![20191212_200841](https://user-images.githubusercontent.com/7836767/70786502-164d9980-1d8d-11ea-9fdb-4e6dcb9e14b7.jpg)
![20191212_200751](https://user-images.githubusercontent.com/7836767/70786503-164d9980-1d8d-11ea-982f-2f0c10d4905f.jpg)
![IMG_20191212_154404](https://user-images.githubusercontent.com/7836767/70786504-164d9980-1d8d-11ea-82d8-14228ad1ddbf.jpg)
![IMG_20191210_190646](https://user-images.githubusercontent.com/7836767/70786505-16e63000-1d8d-11ea-8bcb-c33a41f280a5.jpg)

More questions:
- what was the purpose here rhmiWidth - 280 of substructing 280px (side widget?)
- and why you chose in this line the min value ?
- "menuMap" ->map.changeImageSize(720, 360) - brake the main screen and I dont get any map displayed. 
- i think the function private fun sendImage(bitmap: Bitmap) is a problem here, as it checks for sized that are odd for newer screens and dont correlate with values I changed upwards.

**Comment by hufman** [comment]
Wow, this is some old code :) Let me see if I can remember why I did things this way...

The internal screen resolution, as you discovered, is set in the VirtualDisplayScreenCapture. Those first pictures you posted of the blurry map shouldn't be related to that, because the location blue dot and the Google logo are rendered at the proper quality.
This app's MapView doesn't have access to the official Google Map app's cached tiles, so it's much more dependent on the internet connection, and perhaps that's what is causing a blurry map?

I haven't figured out too much about the properties, beyond their IDs and names and some example values I've seen, which I've saved at the [bottom of this page](https://hufman.github.io/BMWConnectedAnalysis/rhmi-resources/).

I think subtracting 280 was my estimation of how many pixels are lost to the left edge of the screen. I didn't test too hard with it though, I just extrapolated from my 1280 screen looking good with an 1000 image.
I use the min() expression to use that calculated width if the screen's width is small, or the 700/1000 size if the screen is big enough.

menuMap is the little preview map in the menu. From the testing in my car, I could only get it up to a height of 90. It's shown inside a list widget, and each list row can only be two lines of text tall, it seems. You probably only want to change the mainMap size with the mapWidth and mapHeight variables.
sendImage uses this maximum height of 90 to decide whether an incoming frame from the map virtual display should go to the menu or the main screen. There's a slight lag between changing the mode and the next frame using the new size, so I examine the image itself to decide which widget to send it to.

You should try editing the VirtualDisplayScreenCapture.compressBitmap() function to use a lower JPEG quality. From some examples I've tried, 85 is way overkill and I don't even notice a problem with 50, which appears to reduce the image size, and thus frame transfer time, by 33%. If that works out, please try a few values and let me know what quality value looks like a good compromise between speed and clarity! I have plans to make it dynamically lower-quality when you are zooming in and out.

Thank you again for testing this with me :)

**Comment by jezikk82** [comment]
Hi, I've already start playing with size and quality from VirtualDisplayScreenCapture.
I decrease quality to 65 and also dpi to 200 and increase size to 1920x720.
Negative values to position only move the border box reserve by "back arrow" on the left and multimedia info on top right corner. (as on the pic above). So to get it working as regular map we have to figure out hot to change box model, and how to pass positioning absolute instead of relative. 

The page rhmi-resources I already knew and used.

**Comment by jezikk82** [comment]
![IMG_20191216_160002](https://user-images.githubusercontent.com/7836767/70933145-aa448d00-203b-11ea-8d64-9d0f13fc3899.jpg)

I almost finished testing it with gmaps. Results are quite good. I get around 2-3 fps.

Bug, i see is that after I find a result it neither shown on map nor start navi.

**Comment by jezikk82** [comment]
I found optimal settings and map images size to get nice results of presenting map on the idrive screen. 
Map is presented in the full screen mode (exactly the same as original map, no black space around), with and without sidebar, refresh rate in ma case was 2-3 FPS on my setup (highest resolution, mid-range phone). 
Later today I'll prepare files and comment changes I've made and prepare pull request. 

![IMG_20191217_131951](https://user-images.githubusercontent.com/7836767/70996785-cd228000-20d3-11ea-8b72-d0a7f83a1961.jpg)

**Comment by jezikk82** [comment]
If you manage to merge the PR and add missing stuff before weekend I'd be able to test the app in 1-2 more different BMW cars.  

@All we need more testers especially with different resolutions (oldest and newest cars). 
I tested it in both resolutions:
1280 x 480
1440 x 540

**Comment by hufman** [comment]
Ah, I also realized the cause of your point about the map freezing and not updating for several seconds: It's because I only request the phone's position every 5 seconds. I can change that easily.

**Comment by jezikk82** [comment]
Let me know where to change it so I can test it in deeper.

**Comment by c-radu** [comment]
Hello,
I have a BMW series 5 from 2016, with navigation professional, NBT (not NBT EVO ! ).
I rebuild the app today and try it in the car and and found the following issues:
- there is a diagonal red line starting from the left of the screen to the buttom- see attached image. Is any way to remove it ?
- is any way to show the map in really full screen ? I can do some tests if needed.
- searching for places worked fine after I connect the phone to the car, but after i went out and then back to gmap, it does not find any places anymore. Disconnect everything and reconned fix the problem, but i had this issue more than once
- searching for any places does not make sense if you cannot navigate to them. Is any way to do that, something like we did to enable google maps .. ?

![20200412_221330](https://user-images.githubusercontent.com/61106341/79077972-c7e5e280-7d0d-11ea-92fd-2cb18cbd1040.jpg)

**Comment by hufman** [comment]
Whoa I didn't get any notifications for this thread, I sincerely apologize!
@jezikk82 The place to change the location update is [here](https://github.com/hufman/AndroidAutoIdrive/blob/1.2/app/src/gmap/java/me/hufman/androidautoidrive/carapp/maps/GMapsController.kt#L112). When I add the ability to use the car's GPS in #48, I want to update more frequently.
The orange line is something I've never seen before, but I've been developing mainly for Mini. Maybe it is a line connecting to the menu that I use to detect scroll events? Try changing the [position of the list](https://github.com/hufman/AndroidAutoIdrive/blob/1.2/app/src/main/java/me/hufman/androidautoidrive/carapp/maps/MapView.kt#L149) to some negative number or straight down with an X of 0.
I will investigate this bug about losing the navigation status. I intend it to [redraw the navigation](https://github.com/hufman/AndroidAutoIdrive/blob/1.2/app/src/gmap/java/me/hufman/androidautoidrive/carapp/maps/GMapsController.kt#L323) whenever it shows the map after inactivity, and there's even [code to redraw navigation](https://github.com/hufman/AndroidAutoIdrive/blob/1.2/app/src/gmap/java/me/hufman/androidautoidrive/carapp/maps/GMapsController.kt#L96) after the map object is recreated when restarting the projection!

I will be focusing a lot of attention on this module for version 1.4, and I've tagged this Issue because of all the good contributions in it.

**Comment by jezikk82** [comment]
I dont have in 3 different cars any orange line. Maybe it's connected with older NBT. 

p.s. I also lost notifications on this topics. :/

**Comment by c-radu** [comment]
I did some tests and play with the values of positionX and positionY from MapView.kt. The best option found so far to hide that orange line was when I set mapInputList.setProperty(20,-50000) and mapInputList.setProperty(21,0). See attached picture.
![20200508_223147](https://user-images.githubusercontent.com/61106341/81975013-15b47a00-962f-11ea-9427-30f18487b343.jpg)

**Comment by hufman** [comment]
@c-radu That looks so much better, thanks for working on this!
I just merged a big refactor of the Maps UI code to help with external contributions. Please submit a PR to change the inputList positioning [in this file](https://github.com/hufman/AndroidAutoIdrive/blob/afd97bf138338892d932eec0afaa260dced6a9f0/app/src/main/java/me/hufman/androidautoidrive/carapp/FullImageView.kt#L86) and I'll merge your work.

**Comment by hufman** [comment]
@c-radu Would you still like to provide a PR for this fix? I'd love to give you the credit for fixing this bug!

**Comment by jezikk82** [comment]
Hi, I tested your last updated and is almost everything as it should be. 
Small adjustments I'd recommend:
1. GMapController.kt - set startZoom to value ~ 15/currentZoom ~18
2. FullImageView.kt
    - if we want to achieve result like in factory map we should set as follow: imageComponent.setProperty(RHMIProperty.PropertyId.POSITION_Y.id, -80) and LEFT_MARGIN = 0
    -  if we want effect as we have now we need to subtract 80px from rhmiHeight for top bar. 

Moreover, if you can please add option to change map type between regular map and hybrid map. 
(All you need it to add map.setMapType(GoogleMap.MAP_TYPE_HYBRID) in GMapProjection.kt to get hybrid map work)

**Comment by hufman** [comment]
I definitely prefer the full screen view that the -80 POSITION_Y provides in your car. In my ID5/6 generation Mini, the car's map hides most of the status bar, but the app's map has a status bar covering up the whole screen.
Another very strange behavior in my car is: it claims to have an hmi_height of 480, and so the image height is set to this 480, but moving it up -80 under the status bar shows a large gap underneath.
I wonder if my car is secretly a 1440x540 model and only reports an HMI of 1280x480 because that's the allowed app area, what with the curve-y side bars? Does your 1440x540 car report that value in the capabilities view? (Click through the Waiting for Connection bar and Show Advanced Settings to view the list). Do you have an `a4axl: true` value different than mine?
![photo5690823116376352692](https://user-images.githubusercontent.com/1592375/102706908-dc8a5b00-424a-11eb-9c60-b9cea2f0a356.jpg)

**Comment by jezikk82** [comment]
I have a4axl: false in g30 idrive 6.

**Comment by hufman** [comment]
I've [prepared a module](https://github.com/hufman/AndroidAutoIdrive/blob/master/app/src/main/java/me/hufman/androidautoidrive/carapp/RHMIDimensions.kt) to provide different padding measurements for different models of cars. I've measured my MINI ID5 XL car (it was in fact a 1440x540 screen) and made guesses on your cars, can you confirm the exact numbers that fit your cars? Are you able to test ID4, or can @c-radu help with measuring the ID4 padding?
I'll add those other map options in a separate commit(s)!
![photo5740192567147997106](https://user-images.githubusercontent.com/1592375/103733118-d5c74c00-4f9d-11eb-8130-149a323af50c.jpg)

**Comment by jezikk82** [comment]
@hufman In following days I'll try to test it in G30 (BMW5), G01 (X3) - both have the 1440x540 screen&ID6 and F48 (X1) with 1280x480 screen&ID5 and adjust the values. 

Thanks for introducing the hybrid mode & 3d buildings. Share feedback after I finish testing.

**Comment by hufman** [comment]
Hmmm I think this is complete, do you agree?

**Comment by jezikk82** [comment]
Yes, I think so. Nobody reported nothing about it.
